### ISSUE TITLE
About the error in the demo file

### ISSUE THREAD

**Issue by mostar39** [muelea/smplify-xmc#4]
About the error in the demo file

Hello. I am a student who has just started human 3d reconstruction research in Korea.
I found smplify-xmc and it worked really well for what I was looking for.
So I tried running the demo file, but an error occurred, but I don't know how to solve it, so I'm writing this.

Thank you very much for your reply

----------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "main_singleview.py", line 244, in <module>
    main(**args)
  File "main_singleview.py", line 234, in main
    **args)
  File "/home/ylab/smplify-xmc/lib/core/fit_single_frame.py", line 228, in fit_single_frame
    body_model)
  File "/home/ylab/smplify-xmc/lib/core/fitting.py", line 76, in run_fitting
    loss = optimizer.step(closure)
  File "/home/ylab/anaconda3/envs/smplify-xmc/lib/python3.7/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/ylab/smplify-xmc/lib/optimizers/lbfgs_ls.py", line 305, in step
    orig_loss = closure()
  File "/home/ylab/smplify-xmc/lib/core/fitting.py", line 132, in fitting_func
    gt_weight=weight,
  File "/home/ylab/anaconda3/envs/smplify-xmc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ylab/smplify-xmc/lib/core/losses.py", line 299, in forward
    self.sc_crit(vertices=body_model_output.vertices)
  File "/home/ylab/anaconda3/envs/smplify-xmc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ylab/anaconda3/envs/smplify-xmc/lib/python3.7/site-packages/selfcontact/losses/general_selfcontact_loss.py", line 80, in forward
    test_segments=self.test_segments
  File "/home/ylab/anaconda3/envs/smplify-xmc/lib/python3.7/site-packages/selfcontact/selfcontact/selfcontact.py", line 219, in segment_vertices
    vertices, v2v_min, incontact, exterior, test_segments)
  File "/home/ylab/anaconda3/envs/smplify-xmc/lib/python3.7/site-packages/selfcontact/selfcontact/selfcontact.py", line 339, in segment_hd_points
    hd_v2v[:, ~self.geomask] = inf_tensor
IndexError: The shape of the mask [10475, 10475] at index 0 does not match the shape of the indexed tensor [1, 1593, 1593] at index 1
----------------------------------------------------------------------------------------------------------------------------------------

**Comment by mostar39** [comment]
Ubuntu 18.04 
pytorch 1.8.1
cudnn 8.2.1

**Comment by mostar39** [comment]
python main_singleview.py --config configs/fit_smplx_singleview.yaml \
--dataset mtp_demo \
--input_base_dir data/example_input/singleview/subject1 \
--input_dir_poses data/example_input/presented_poses \
--output_dir data/example_output/singleview/subject1 \
--model_folder $MODELS_FOLDER


$MODELS_FOLDER change

**Comment by muelea** [comment]
Thanks for pointing this out! 

It's a bug introduced in the second version of the selfcontact package 0.2.0. It's fixed now. Please, pull the lastest version of the selfcontact package and install it again in your smpify-xmc environment.

https://github.com/muelea/selfcontact/commit/08da422526419c24736c0616bca49623e442c26a

**Comment by mostar39** [comment]
Thank you very, very much!!!
I didn't expect to get an answer today, but thank you so much for answering and fixing the bug.

It's working normally now.

Thank you so much again, and I wish you all the best!
