### ISSUE TITLE
data type issue (or GPU memory issue?) on "vert_ids_wt"

### ISSUE THREAD

**Issue by stnoh** [muelea/smplify-xmc#5]
Hello, I recently would like to reproduce your code & data in my environment, but I encountered a small problem.
This is the spec of my PC & setting.
- OS: **Windows 10**
- CPU: Core i7-8700 (3.2GHz) / RAM 32G / GPU: GTX 1080 Ti (11GB)
- Python: 3.8.10 (anaconda 2021.05) / Pytorch: 1.8.0 / CUDA 10.1.243

I followed your instruction and run ``main_singleview.py``.  
It seemed to work well until 67%... However, it suddenly stopped with the following error message:
```sh
Traceback (most recent call last):
  File "main_singleview.py", line 244, in <module>
    main(**args)
  File "main_singleview.py", line 207, in main
    fit_single_frame(img,
  File "{path to git clone}\lib\core\fit_single_frame.py", line 224, in fit_single_frame
    final_loss_val = monitor.run_fitting(
  File "{path to git clone}\lib\core\fitting.py", line 76, in run_fitting
    loss = optimizer.step(closure)
  File "{my user account}\.conda\envs\venv_pt\lib\site-packages\torch\optim\optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "{path to git clone}\lib\optimizers\lbfgs_ls.py", line 305, in step
    orig_loss = closure()
  File "{path to git clone}\lib\core\fitting.py", line 125, in fitting_func
    total_loss = loss(
  File "{my user account}\.conda\envs\venv_pt\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "{path to git clone}\lib\core\losses.py", line 299, in forward
    self.sc_crit(vertices=body_model_output.vertices)
  File "{my user account}\.conda\envs\venv_pt\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "{my user account}\.conda\envs\venv_pt\lib\site-packages\selfcontact-0.2.0-py3.8.egg\selfcontact\losses\general_selfcontact_loss.py", line 77, in forward
  File "{my user account}\.conda\envs\venv_pt\lib\site-packages\selfcontact-0.2.0-py3.8.egg\selfcontact\selfcontact.py", line 196, in segment_vertices
  File "{my user account}\.conda\envs\venv_pt\lib\site-packages\selfcontact-0.2.0-py3.8.egg\selfcontact\selfcontact.py", line 122, in triangles
IndexError: tensors used as indices must be long, byte or bool tensors
```

I am not familiar with this error, but it seemed that ``vert_ids_wt`` in ``selfcontact`` is problematic.
https://github.com/muelea/selfcontact/blob/master/selfcontact/selfcontact.py#L78

I examined the data from ``smplx_inner_mouth_bounds.pkl``. It is just an array of integer values ``[8958 1666 1665 ... 8958]`` became ``np.int32`` to ``torch.int32`` (``Int``), so I forcefully changed it as ``Long`` like this:
```Python
#self.register_buffer('vert_ids_wt', torch.from_numpy(vert_ids_wt))
self.register_buffer('vert_ids_wt', torch.from_numpy(vert_ids_wt.astype(np.int64))) ## [QUICK FIX for Windows]
```

However, I still encountered a problem at the same location with a different error message:
```sh
  File "{my user account}\.conda\envs\venv_pt\lib\site-packages\selfcontact-0.2.0-py3.8.egg\selfcontact\losses\general_selfcontact_loss.py", line 77, in forward
  File "{my user account}\.conda\envs\venv_pt\lib\site-packages\selfcontact-0.2.0-py3.8.egg\selfcontact\selfcontact.py", line 200, in segment_vertices
  File "{my user account}\.conda\envs\venv_pt\lib\site-packages\selfcontact-0.2.0-py3.8.egg\selfcontact\selfcontact.py", line 141, in get_intersection_mask
  File "{my user account}\.conda\envs\venv_pt\lib\site-packages\selfcontact-0.2.0-py3.8.egg\selfcontact\utils\mesh.py", line 223, in winding_numbers
  File "{my user account}\.conda\envs\venv_pt\lib\site-packages\selfcontact-0.2.0-py3.8.egg\selfcontact\utils\mesh.py", line 164, in solid_angles
RuntimeError: CUDA out of memory. Tried to allocate 438.00 MiB (GPU 0; 11.00 GiB total capacity; 9.64 GiB already allocated; 0 bytes free; 9.65 GiB reserved in total by PyTorch)
```

So, here are my two questions.
1. Was it ok to change ``vert_ids_wt`` as ``np.int64``/``torch.int64``? If not, do you have any suggestions to fix this issue?
2. If it is, do I need more (GPU) memory to run this code?

Thank you in advance.

**Comment by muelea** [comment]
Hi,

I just came across your questions, sorry for the delay. 

Regarding 1., you can change the data type to either np.int64 / torch.int64. The array is just used to index the mesh vertices and close the back of the mouth. 

Regarding 2., the code was tested with a Quadro P5000 (16 GB), which is needed during inside outside segmentation in the selfcontact package. Here are some suggestions how you can fix it and run the optimization with less memory: https://github.com/muelea/selfcontact/issues/4

All the best,
Lea
